# Tardis project

We, Loup, Lukas and Eva are part of a newly formed **SNCF Data Analysis Service**, dedicated to improving the efficiency of train travel across the country.

Our mission? Analyze historical train delay data, uncover hidden patterns, and develop a predictive model that can forecast delays before they happen. The SNCF has entrusted our team with making the railway system more efficient and transparent.

If we <span style="color:green">succeed</span>, our dashboard will be used by thousands of travelers to better plan their journeys. If we <span style="color:red">fail</span>... well, we expect a lot more unhappy commuters. 

No pressure! Using the provided dataset, our job is to clean and analyze historical delay data, develop a simple predictive model, and present our insights through an interactive **Streamlit dashboard**.

In [1]:
#Importing the library to manage the dataset
import pandas as pd

# Step 1 : Data exploration and cleaning
## 1. Reading csv

Printing names of columns, number of columns and number of rows

In [2]:
df = pd.read_csv("dataset.csv", sep=";")
print("Column names are: ")
#We get names of columns in the Dataframe
columns = df.columns
for i in range(len(columns) - 1):
    print(columns[i], end=", ")
print(columns[-1])

Column names are:
Date, Service, Departure station, Arrival station, Average journey time, Number of scheduled trains, Number of cancelled trains, Cancellation comments, Number of trains delayed at departure, Average delay of late trains at departure, Average delay of all trains at departure, Departure delay comments, Number of trains delayed at arrival, Average delay of late trains at arrival, Average delay of all trains at arrival, Arrival delay comments, Number of trains delayed > 15min, Average delay of trains > 15min (if competing with flights), Number of trains delayed > 30min, Number of trains delayed > 60min, Pct delay due to external causes, Pct delay due to infrastructure, Pct delay due to traffic management, Pct delay due to rolling stock, Pct delay due to station management and equipment reuse, Pct delay due to passenger handling (crowding, disabled persons, connections)

**Statistics on Dataframe per column**
- count : how many datas.
- unique : how many unique values.
- top : most common value.
- freq : most common value’s frequency.

In [3]:
description = df.describe()
display(description)

#We print the dataframe
print("\nHere's the original dataset:")
display(df)

#We get number of line and columns in the Dataframe
nb_line_start, nb_col_start = df.shape
print(f"\nThere is {nb_col_start} columns and {nb_line_start} line in original dataset.")

,Date,Service,Departure station,Arrival station,Average journey time,Number of scheduled trains,Number of cancelled trains,Cancellation comments,Number of trains delayed at departure,Average delay of late trains at departure,...,Number of trains delayed > 15min,Average delay of trains > 15min (if competing with flights),Number of trains delayed > 30min,Number of trains delayed > 60min,Pct delay due to external causes,Pct delay due to infrastructure,Pct delay due to traffic management,Pct delay due to rolling stock,Pct delay due to station management and equipment reuse,"Pct delay due to passenger handling (crowding, disabled persons, connections)"
count,12010,11830,12011,12011,11829,11830,11831,577,11830,11831,...,11828,11831,11832,11833,11828,11827,11829,11827,11828,11830
unique,318,2,132,116,652,1034,248,3,629,11162,...,265,11075,175,96,2732,2592,2677,2535,2130,2172
top,2025-09,National,PARIS LYON,PARIS LYON,96.0,31.0,0.0,Non communiqué,13.0,0.0,...,10.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
freq,135,10370,2405,2413,184,117,3917,196,161,134,...,327,218,779,1760,1100,1021,1326,1220,3361,3809

Here's the original dataset:

,Date,Service,Departure station,Arrival station,Average journey time,Number of scheduled trains,Number of cancelled trains,Cancellation comments,Number of trains delayed at departure,Average delay of late trains at departure,...,Number of trains delayed > 15min,Average delay of trains > 15min (if competing with flights),Number of trains delayed > 30min,Number of trains delayed > 60min,Pct delay due to external causes,Pct delay due to infrastructure,Pct delay due to traffic management,Pct delay due to rolling stock,Pct delay due to station management and equipment reuse,"Pct delay due to passenger handling (crowding, disabled persons, connections)"
0,01-2018,National,BORDEAUX ST JEAN,PARIS MONTPARNASSE,141.0 min,870,5.0,NaN,289.0,11.24780854,...,110.0,6.51,44.0,8.0,36.13445378,31.09243697,10.92436975,15.96638655,"5,04",0.840336134
1,2018-01,National,LE MANS,PARIS MONTPARNASSE,NaN,406.0,1.0,NaN,213.0,8.479968701,...,32.0,5.363539095,9.0,4.0,20.0,35.0,16.66666667,16.66666667,8.333333333,3.333333333
2,2018-01,National,PARIS MONTPARNASSE,LA ROCHELLE VILLE,166.0,226.0,0.0,NaN,21.0,6.23968254,...,11.0,2.938053097,6.0,1.0,22.22222222,27.77777778,16.66666667,16.66666667,5.555555556,11.11111111
3,2018-01,National,PARIS MONTPARNASSE,NANTES,216.21,508.0,3.0,NaN,71.0,7.235211268,...,39.0,5.292211221,18.0,NaN,33.33333333,22.22222222,16.66666667,20.37037037,5.555555556,1.851851852
4,2018-01,National,POITIERS,PARIS MONTPARNASSE,94.0,472.0,4.0,NaN,224.0,6.784672619,...,42.0,4.882371795,10.0,0.0,15.78947368,45.61403509,NaN,15.78947368,1.754385965,1.754385965
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12065,2020-09,National,LE CREUSOT MONTCEAU MONTCHANIN,PARIS LYON,84.0,214.0,2.0,NaN,164.0,NaN,...,10.0,41.27037037,6.0,NaN,18.18181818,22.727,40.90909091,0.0,NaN,4.545454545
12066,2024-05,National,BORDEAUX ST JEAN,TOURCOING,313.0,30.0,0.0,NaN,4.0,3.775,...,9.0,25.333333333,3.0,0.0,0.0,44.444444440000005,22.22%,11.11111111,11.11111111,11.11111111
12067,2018-08,National,PARIS MONTPARNASSE,ST PIERRE DES CORPS,67.0,358.0,2.0,NaN,53.0,8.623584906,...,13.0,3.636938202,5.0,3.0,12.19512195,24.3902439,24.3902439,31.70731707,4.87804878,2.43902439
12068,2018-03,National,PARIS LYON,ANNECY,226.0,196.0,5.0,NaN,30.0,17.57333333,...,32.0,9.188481675,11.0,5.0,20.68965517,NaN,31.03448276,24.13793103,0.0,0.0
12069,2019-01,National,PARIS MONTPARNASSE,ANGOULEME,127.0,297.0,5.0,NaN,42.0,18.82738095,...,23.0,5.537271689,10.0,8.0,36.36363636,9.090909091,27.27272727,21.21212121,0.0,6.060606061

There is 26 columns and 12070 line in original dataset.

## 2. Remove duplicate entries

In [4]:
#This function return a Dataframe with the duplicates rows removed
df = df.drop_duplicates()

nb_line1, nb_col2 = df.shape
print(f"There is {nb_col2} columns and {nb_line1} line in the new dataset. {nb_line_start - nb_line1} lines has been removed.")

There is 26 columns and 11896 line in the new dataset. 174 lines has been removed.

## 3. Cleaning dataset

### Date column
This column references the month and year observed for the trains.
1. Put date at correct format: YEAR-MONTH, remove spaces at the start and end of string and set correct hyphen

In [5]:
#We get the values at column Date and put them to date format of pandas
df["Date"] = pd.to_datetime(df["Date"], yearfirst=True, format='mixed')

#Forcing format to be YEAR-MONTH
df["Date"] = df["Date"].dt.strftime("%Y-%m")

2. Check if the nearby dates are identical; if the current date does not have one, replace it, otherwise delete the line because it is too important data.

In [6]:
values = df["Date"]

indexes = []
index_df = df.index
for i in index_df:
    value_str = str(values[i]).lower().strip()
    if value_str == "null" or value_str == "nan" or pd.isnull(values[i]):
        if i > 0 and i < len(values) - 1 and values[i - 1] == values[i + 1]:
            values[i] = values[i - 1]
        else:
            indexes.append(i)
df.update(values)

#Removing rows with dates unrectifable
df.drop(indexes, inplace=True)
nb_line2, nb_col2 = df.shape
print(f"There is {nb_col2} columns and {nb_line2} line in the new dataset. {nb_line1 - nb_line2} lines has been removed.")

There is 26 columns and 11895 line in the new dataset. 1 lines has been removed.

### Service
If something else than "National" or "International", we put the value at NaN.

In [7]:
values = df["Service"]
nb_modified = 0

for i in range(len(values)):
    value_str = str(values.iloc[i]).lower()
    if value_str != "national" and value_str != "international":
        values.iloc[i] = pd.NaT
        nb_modified += 1
df.update(values)

print(f"{nb_modified} cells has been modified.")

240 cells has been modified.

## Departure station

Delete every line without a departure station and puts them in uppercases

In [8]:
values = df["Departure station"]

for i in range(len(values)):
    value_str = str(values.iloc[i]).upper()
    if value_str == "NAN" or value_str == "NULL":
        df.drop(i, inplace=True)

nb_line2, nb_col2 = df.shape
print(f"There is {nb_col2} columns and {nb_line2} line in the new dataset. {nb_line1 - nb_line2} lines has been removed.")

There is 26 columns and 11836 line in the new dataset. 60 lines has been removed.

## Arrival station
Delete every line without a departure station and puts them in uppercases

In [9]:
values = df["Arrival station"]

for i in range(len(values)):
    value_str = str(values.iloc[i]).upper()
    if value_str == "NAN" or value_str == "NULL":
        df.drop(i, inplace=True)

nb_line2, nb_col2 = df.shape
print(f"There is {nb_col2} columns and {nb_line2} line in the new dataset. {nb_line1 - nb_line2} lines has been removed.")

There is 26 columns and 11777 line in the new dataset. 119 lines has been removed.

## Average journey time

Correct the format of the average journey time

1. Replace empty cells with -1 (-1 = No data, and will not be used for statistics)

In [10]:
values = df["Average journey time"]
nb_modified = 0

for i in range(len(values)):
    if pd.isnull(values.iloc[i]):
        values.iloc[i] = "-1"
        nb_modified += 1

df.update(values)
print(f"{nb_modified} cells has been modified.")

237 cells has been modified.

2. Remove "min" from cells

In [11]:
values = df["Average journey time"]
nb_modified = 0

for i in range(len(values)):
    if values.iloc[i].find("min") != -1:
        values.iloc[i] = values.iloc[i].replace("min", "")
        nb_modified += 1
    values.iloc[i] = values.iloc[i].strip()

df.update(values)
print(f"{nb_modified} cells has been modified.")

66 cells has been modified.

## Number of scheduled trains

Correct the format of the number of scheduled trains

Replace empty cells with -1 (-1 = No data, and will not be used for statistics)

In [12]:
values = df["Number of scheduled trains"]
nb_modified = 0

for i in range(len(values)):
    if pd.isnull(values.iloc[i]):
        values.iloc[i] = "-1"
        nb_modified += 1

df.update(values)
print(f"{nb_modified} cells has been modified.")

233 cells has been modified.

## Number of cancelled trains

Correct the format of the number of cancelled trains

Replace empty cells with -1 (-1 = No data, and will not be used for statistics)

In [13]:
values = df["Number of cancelled trains"]
nb_modified = 0

for i in range(len(values)):
    if pd.isnull(values.iloc[i]):
        values.iloc[i] = "-1"
        nb_modified += 1

df.update(values)
print(f"{nb_modified} cells has been modified.")

235 cells has been modified.

## Cancellation comments

Cancellation comments removed because there is no data inside it

In [14]:
df = df.drop("Cancellation comments", axis=1)

print("New column names are: ")
#We get names of columns in the Dataframe
columns = df.columns
for i in range(len(columns) - 1):
    print(columns[i], end=", ")
print(columns[-1])

New column names are:
Date, Service, Departure station, Arrival station, Average journey time, Number of scheduled trains, Number of cancelled trains, Number of trains delayed at departure, Average delay of late trains at departure, Average delay of all trains at departure, Departure delay comments, Number of trains delayed at arrival, Average delay of late trains at arrival, Average delay of all trains at arrival, Arrival delay comments, Number of trains delayed > 15min, Average delay of trains > 15min (if competing with flights), Number of trains delayed > 30min, Number of trains delayed > 60min, Pct delay due to external causes, Pct delay due to infrastructure, Pct delay due to traffic management, Pct delay due to rolling stock, Pct delay due to station management and equipment reuse, Pct delay due to passenger handling (crowding, disabled persons, connections)

## Number of trains delayed at departure

Correct the format of the number of trains delayed at departure

Replace empty cells with -1 (-1 = No data, and will not be used for statistics)

In [15]:
values = df["Number of trains delayed at departure"]
nb_modified = 0

for i in range(len(values)):
    if pd.isnull(values.iloc[i]):
        values.iloc[i] = "-1"
        nb_modified += 1

df.update(values)
print(f"{nb_modified} cells has been modified.")

235 cells has been modified.

## Average delay of late trains at departure

Correct the format of the average delay of late trains at departure

1. Replace empty cells with -1 (-1 = No data, and will not be used for statistics)

In [16]:
values = df["Average delay of late trains at departure"]
nb_modified = 0

for i in range(len(values)):
    if pd.isnull(values.iloc[i]):
        values.iloc[i] = "-1"
        nb_modified += 1

df.update(values)
print(f"{nb_modified} cells has been modified.")

236 cells has been modified.

2. Remove "min" from cells

In [17]:
values = df["Average delay of late trains at departure"]
nb_modified = 0

for i in range(len(values)):
    if values.iloc[i].find("min") != -1:
        values.iloc[i] = values.iloc[i].replace("min", "")
        nb_modified += 1
    values.iloc[i] = values.iloc[i].strip()

df.update(values)
print(f"{nb_modified} cells has been modified.")

57 cells has been modified.

## Average delay of all trains at departure

Correct the format of the number of the average delay of all trains at departure

1. Replace empty cells with -1 (-1 = No data, and will not be used for statistics)

In [18]:
values = df["Average delay of all trains at departure"]
nb_modified = 0

for i in range(len(values)):
    if pd.isnull(values.iloc[i]):
        values.iloc[i] = "-1"
        nb_modified += 1

df.update(values)
print(f"{nb_modified} cells has been modified.")

235 cells has been modified.

2. Remove "min" from cells

In [19]:
values = df["Average delay of all trains at departure"]
nb_modified = 0

for i in range(len(values)):
    if values.iloc[i].find("min") != -1:
        values.iloc[i] = values.iloc[i].replace("min", "")
        nb_modified += 1
    values.iloc[i] = values.iloc[i].strip()

df.update(values)
print(f"{nb_modified} cells has been modified.")

58 cells has been modified.

## Departure delay comments

Departure delay comments removed because there is no data inside it

In [20]:
df = df.drop("Departure delay comments", axis=1)

print("New column names are: ")
#We get names of columns in the Dataframe
columns = df.columns
for i in range(len(columns) - 1):
    print(columns[i], end=", ")
print(columns[-1])

New column names are:
Date, Service, Departure station, Arrival station, Average journey time, Number of scheduled trains, Number of cancelled trains, Number of trains delayed at departure, Average delay of late trains at departure, Average delay of all trains at departure, Number of trains delayed at arrival, Average delay of late trains at arrival, Average delay of all trains at arrival, Arrival delay comments, Number of trains delayed > 15min, Average delay of trains > 15min (if competing with flights), Number of trains delayed > 30min, Number of trains delayed > 60min, Pct delay due to external causes, Pct delay due to infrastructure, Pct delay due to traffic management, Pct delay due to rolling stock, Pct delay due to station management and equipment reuse, Pct delay due to passenger handling (crowding, disabled persons, connections)

## Number of trains delayed at arrival

Correct the format of the number of the number of trains delayed at arrival

Replace empty cells with -1 (-1 = No data, and will not be used for statistics)

In [21]:
values = df["Number of trains delayed at arrival"]
nb_modified = 0

for i in range(len(values)):
    if pd.isnull(values.iloc[i]):
        values.iloc[i] = "-1"
        nb_modified += 1

df.update(values)
print(f"{nb_modified} cells has been modified.")

234 cells has been modified.

## Average delay of late trains at arrival

Correct the format of the average delay of late trains at arrival

1. Replace empty cells with -1 (-1 = No data, and will not be used for statistics)

In [22]:
values = df["Average delay of late trains at arrival"]
nb_modified = 0

for i in range(len(values)):
    if pd.isnull(values.iloc[i]):
        values.iloc[i] = "-1"
        nb_modified += 1

df.update(values)
print(f"{nb_modified} cells has been modified.")

231 cells has been modified.

2. Remove "min" from cells

In [23]:
values = df["Average delay of late trains at arrival"]
nb_modified = 0

for i in range(len(values)):
    if values.iloc[i].find("min") != -1:
        values.iloc[i] = values.iloc[i].replace("min", "")
        nb_modified += 1
    values.iloc[i] = values.iloc[i].strip()

df.update(values)
print(f"{nb_modified} cells has been modified.")

62 cells has been modified.

## Average delay of all trains at arrival

Correct the format of the average delay of all trains at arrival

1. Replace empty cells with -1 (-1 = No data, and will not be used for statistics)

In [24]:
values = df["Average delay of all trains at arrival"]
nb_modified = 0

for i in range(len(values)):
    if pd.isnull(values.iloc[i]):
        values.iloc[i] = "-1"
        nb_modified += 1

df.update(values)
print(f"{nb_modified} cells has been modified.")

235 cells has been modified.

2. Remove "min" from cells

In [25]:
values = df["Average delay of all trains at arrival"]
nb_modified = 0

for i in range(len(values)):
    if values.iloc[i].find("min") != -1:
        values.iloc[i] = values.iloc[i].replace("min", "")
        nb_modified += 1
    values.iloc[i] = values.iloc[i].strip()

df.update(values)
print(f"{nb_modified} cells has been modified.")

57 cells has been modified.

## Arrival delay comments

Change every empty cells or cells without comments (NC, NA Non communiqué...)

In [26]:
values = df["Arrival delay comments"]
nb_modified = 0

for i in range(len(values)):
    if pd.isnull(values.iloc[i]) or str(values.iloc[i]).lower().strip() in ["nc", "na", "non communiqué", "null", "nan"]:
        values.iloc[i] = "NC"
        nb_modified += 1

df.update(values)
print(f"{nb_modified} cells has been modified.")

11023 cells has been modified.

## Number of trains delayed > 15min

Correct the format of the number of trains delayed > 15min

1. Replace empty cells with -1 (-1 = No data, and will not be used for statistics)

In [27]:
values = df["Number of trains delayed > 15min"]
nb_modified = 0

for i in range(len(values)):
    if pd.isnull(values.iloc[i]):
        values.iloc[i] = "-1"
        nb_modified += 1

df.update(values)
print(f"{nb_modified} cells has been modified.")

234 cells has been modified.

2. Clean the number

In [28]:
values = df["Number of trains delayed > 15min"]

for i in range(len(values)):
    values.iloc[i] = values.iloc[i].strip()

df.update(values)

## Average delay of trains > 15min (if competing with flights)

Correct the format of the average delay of trains > 15min (if competing with flights)

1. Replace empty cells with -1 (-1 = No data, and will not be used for statistics)

In [29]:
values = df["Average delay of trains > 15min (if competing with flights)"]
nb_modified = 0

for i in range(len(values)):
    if pd.isnull(values.iloc[i]):
        values.iloc[i] = "-1"
        nb_modified += 1

df.update(values)
print(f"{nb_modified} cells has been modified.")

233 cells has been modified.

2. Clean the number

In [30]:
values = df["Average delay of trains > 15min (if competing with flights)"]

for i in range(len(values)):
    values.iloc[i] = values.iloc[i].strip()

df.update(values)

## Number of trains delayed > 30min

Correct the format of the number of trains delayed > 30min

1. Replace empty cells with -1 (-1 = No data, and will not be used for statistics)

In [31]:
values = df["Number of trains delayed > 30min"]
nb_modified = 0

for i in range(len(values)):
    if pd.isnull(values.iloc[i]):
        values.iloc[i] = "-1"
        nb_modified += 1

df.update(values)
print(f"{nb_modified} cells has been modified.")

233 cells has been modified.

2. Clean the number

In [32]:
values = df["Number of trains delayed > 30min"]

for i in range(len(values)):
    values.iloc[i] = values.iloc[i].strip()

df.update(values)

## Number of trains delayed > 60min

Correct the format of the number of trains delayed > 60min

1. Replace empty cells with -1 (-1 = No data, and will not be used for statistics)

In [33]:
values = df["Number of trains delayed > 60min"]
nb_modified = 0

for i in range(len(values)):
    if pd.isnull(values.iloc[i]):
        values.iloc[i] = "-1"
        nb_modified += 1

df.update(values)
print(f"{nb_modified} cells has been modified.")

231 cells has been modified.

2. Clean the number

In [34]:
values = df["Number of trains delayed > 60min"]

for i in range(len(values)):
    values.iloc[i] = values.iloc[i].strip()

df.update(values)

## Pct delay due to external causes

Correct the format of the Pct delay due to external causes

1. Replace empty cells with -1 (-1 = No data, and will not be used for statistics)

In [35]:
values = df["Pct delay due to external causes"]
nb_modified = 0

for i in range(len(values)):
    if pd.isnull(values.iloc[i]):
        values.iloc[i] = "-1"
        nb_modified += 1

df.update(values)
print(f"{nb_modified} cells has been modified.")

236 cells has been modified.

2. Clean the number

In [36]:
values = df["Pct delay due to external causes"]

for i in range(len(values)):
    values.iloc[i] = values.iloc[i].strip()

df.update(values)

## Pct delay due to infrastructure

Correct the format of the pct delay due to infrastructure

1. Replace empty cells with -1 (-1 = No data, and will not be used for statistics)

In [37]:
values = df["Pct delay due to infrastructure"]
nb_modified = 0

for i in range(len(values)):
    if pd.isnull(values.iloc[i]):
        values.iloc[i] = "-1"
        nb_modified += 1

df.update(values)
print(f"{nb_modified} cells has been modified.")

231 cells has been modified.

2. Clean the number

In [38]:
values = df["Pct delay due to infrastructure"]

for i in range(len(values)):
    values.iloc[i] = values.iloc[i].strip()

df.update(values)

## Pct delay due to traffic management

Correct the format of the pct delay due to traffic management

1. Replace empty cells with -1 (-1 = No data, and will not be used for statistics)

In [39]:
values = df["Pct delay due to traffic management"]
nb_modified = 0

for i in range(len(values)):
    if pd.isnull(values.iloc[i]):
        values.iloc[i] = "-1"
        nb_modified += 1

df.update(values)
print(f"{nb_modified} cells has been modified.")

236 cells has been modified.

2. Clean the number

In [40]:
values = df["Pct delay due to traffic management"]

for i in range(len(values)):
    values.iloc[i] = values.iloc[i].strip()

df.update(values)

## Pct delay due to rolling stock

Correct the format of the pct delay due to rolling stock

1. Replace empty cells with -1 (-1 = No data, and will not be used for statistics)

In [41]:
values = df["Pct delay due to rolling stock"]
nb_modified = 0

for i in range(len(values)):
    if pd.isnull(values.iloc[i]):
        values.iloc[i] = "-1"
        nb_modified += 1

df.update(values)
print(f"{nb_modified} cells has been modified.")

238 cells has been modified.

2. Clean the number

In [42]:
values = df["Pct delay due to rolling stock"]

for i in range(len(values)):
    values.iloc[i] = values.iloc[i].strip()

df.update(values)

## Pct delay due to station management and equipment reuse

Correct the format of the pct delay due to station management and equipment reuse

1. Replace empty cells with -1 (-1 = No data, and will not be used for statistics)

In [43]:
values = df["Pct delay due to station management and equipment reuse"]
nb_modified = 0

for i in range(len(values)):
    if pd.isnull(values.iloc[i]):
        values.iloc[i] = "-1"
        nb_modified += 1

df.update(values)
print(f"{nb_modified} cells has been modified.")

238 cells has been modified.

2. Clean the number

In [44]:
values = df["Pct delay due to station management and equipment reuse"]

for i in range(len(values)):
    values.iloc[i] = values.iloc[i].strip()

df.update(values)

## Pct delay due to passenger handling (crowding, disabled persons, connections)

Correct the format of the pct delay due to passenger handling (crowding, disabled persons, connections)

1. Replace empty cells with -1 (-1 = No data, and will not be used for statistics)

In [45]:
values = df["Pct delay due to passenger handling (crowding, disabled persons, connections)"]
nb_modified = 0

for i in range(len(values)):
    if pd.isnull(values.iloc[i]):
        values.iloc[i] = "-1"
        nb_modified += 1

df.update(values)
print(f"{nb_modified} cells has been modified.")

235 cells has been modified.

2. Clean the number

In [46]:
values = df["Pct delay due to passenger handling (crowding, disabled persons, connections)"]

for i in range(len(values)):
    values.iloc[i] = values.iloc[i].strip()

df.update(values)

# Dataset after cleaning

In [47]:
old_df = pd.read_csv("dataset.csv", sep=";")

old_nb_line, old_nb_col = old_df.shape
nb_line, nb_col = df.shape

print(f"\nThere is {nb_col} columns and {nb_line} line in the new dataset.\n- {old_nb_line - nb_line} lines has been removed\n- {old_nb_col - nb_col} columns has been removed.\n {((old_nb_line - nb_line) / old_nb_line * 100):.2f}% of the dataset lines were removed")

display(df)

There is 24 columns and 11777 line in the new dataset.
- 293 lines has been removed
- 2 columns has been removed.
 2.43% of the dataset lines were removed

,Date,Service,Departure station,Arrival station,Average journey time,Number of scheduled trains,Number of cancelled trains,Number of trains delayed at departure,Average delay of late trains at departure,Average delay of all trains at departure,...,Number of trains delayed > 15min,Average delay of trains > 15min (if competing with flights),Number of trains delayed > 30min,Number of trains delayed > 60min,Pct delay due to external causes,Pct delay due to infrastructure,Pct delay due to traffic management,Pct delay due to rolling stock,Pct delay due to station management and equipment reuse,"Pct delay due to passenger handling (crowding, disabled persons, connections)"
0,2018-01,National,BORDEAUX ST JEAN,PARIS MONTPARNASSE,141.0,870,5.0,289.0,11.24780854,3.693179191,...,110.0,6.51,44.0,8.0,36.13445378,31.09243697,10.92436975,15.96638655,"5,04",0.840336134
1,2018-01,National,LE MANS,PARIS MONTPARNASSE,-1,406.0,1.0,213.0,8.479968701,4.567119342,...,32.0,5.363539095,9.0,4.0,20.0,35.0,16.66666667,16.66666667,8.333333333,3.333333333
2,2018-01,National,PARIS MONTPARNASSE,LA ROCHELLE VILLE,166.0,226.0,0.0,21.0,6.23968254,0.286283186,...,11.0,2.938053097,6.0,1.0,22.22222222,27.77777778,16.66666667,16.66666667,5.555555556,11.11111111
3,2018-01,National,PARIS MONTPARNASSE,NANTES,216.21,508.0,3.0,71.0,7.235211268,0.98,...,39.0,5.292211221,18.0,-1,33.33333333,22.22222222,16.66666667,20.37037037,5.555555556,1.851851852
4,2018-01,National,POITIERS,PARIS MONTPARNASSE,94.0,472.0,4.0,224.0,6.784672619,3.229700855,...,42.0,4.882371795,10.0,0.0,15.78947368,45.61403509,-1,15.78947368,1.754385965,1.754385965
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12033,2018-11,National,SAINT ETIENNE CHATEAUCREUX,PARIS LYON,168.0,113.0,1.0,19.0,5.662280702,0.854761905,...,14.0,5.510416667,5.0,2.0,21.05263158,36.84210526,5.263157895,21.05263158,10.52631579,5.263157895
12034,2021-05,NaN,PARIS MONTPARNASSE,NANTES,138.0,470.0,29.0,48.0,4.22569444444444,0.151738473167045,...,6.0,31.4527777777778,3.0,0.0,22.2222222222222,0.0,11.1111111111111,33.3333333333333,0.0,33.3333333333333
12049,2018-03,NaN,PERPIGNAN,PARIS LYON,305.0,163.0,1.0,63.0,8.189417989,3.216769547,...,23.0,8.470884774,14.0,7.0,57.14285714,14.28571429,14.28571429,14.28571429,0.0,0.0
12056,2019-02,National,NICE VILLE,PARIS LYON,357.0,159.0,4.0,32.0,6.80625,1.463978495,...,33.0,9.321935484,13.0,5.0,18.18181818,36.36363636,24.24242424,12.12121212,9.090909091,0.0
12060,2022-03,National,Paris Lyon,MULHOUSE VILLE,171.0,264.0,0.0,34.0,18.8730392156863,2.28352272727273,...,23.0,48.861594202898594,17.0,5.0,20.6896551724138,17.2413793103448,17.2413793103448,31.0344827586207,13.7931034482759,0.0